<a href="https://colab.research.google.com/github/DhaiHamoud/Fraud-Detection-in-the-Financial-Transaction-Market/blob/main/notebooks/01_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning

Sections:
1. Initial Inspection
2. Column Types
3. Text Columns
4. Unnecessary Columns
5. Missing Values
6. Duplicates
7. Outliers
8. Summary

In [15]:
import kagglehub, pandas as pd
path = kagglehub.dataset_download('kartik2112/fraud-detection')
train = pd.read_csv(f'{path}/fraudTrain.csv')
test = pd.read_csv(f'{path}/fraudTest.csv')
df = pd.concat([train, test], ignore_index=True)
rows_before = len(df)  #will be used in the summary

Using Colab cache for faster access to the 'fraud-detection' dataset.

## 1. Initial Inspection — Dhai

In [16]:
print(df.shape)
df.info()
df.head()

(1852394, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Unnamed: 0             int64
 1   trans_date_trans_time  object
 2   cc_num                 int64
 3   merchant               object
 4   category               object
 5   amt                    float64
 6   first                  object
 7   last                   object
 8   gender                 object
 9   street                 object
 10  city                   object
 11  state                  object
 12  zip                    int64
 13  lat                    float64
 14  long                   float64
 15  city_pop               int64
 16  job                    object
 17  dob                    object
 18  trans_num              object
 19  unix_time              int64
 20  merch_lat              float64
 21  merch_long             float64
 22  is_fraud               int64
dtypes: float64(5), int64(6), object(12)
memory usage: 325.1+ MB

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

**Notes:**
- 1,852,394 rows and 23 columns
- Target column: `is_fraud` (0 = legitimate, 1 = fraud)
- `trans_date_trans_time` and `dob` are stored as text, not dates
- `cc_num` and `zip` are stored as numbers, but they are IDs
- `Unnamed: 0` is an index column from the original files
- Merchant names start with `fraud_`, even in legitimate transactions
- `first`, `last`, and `street` contain personal information

# 2. Column Types - Turki

In [17]:
df.dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [18]:
# changing the trans_date_trans_time to datetime64[ns] data type
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])

# checking if the change was made
df["trans_date_trans_time"].dtype

dtype('<M8[ns]')

In [19]:
# changing the dob to datetime64[ns] data type
df["dob"] = pd.to_datetime(df["dob"])

# checking if the change was made
df["dob"].dtype

dtype('<M8[ns]')

In [20]:
# changing cc_num to string since its an identifier
df["cc_num"] = df["cc_num"].astype(str)

# checking if the change was made
df["cc_num"].dtype

dtype('O')

In [21]:
# changing zip to a string since its a location code, not a quantity
df["zip"] = df["zip"].astype(str)

# checking if the chnage was made
df["zip"].dtype

dtype('O')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Unnamed: 0             int64
 1   trans_date_trans_time  datetime64[ns]
 2   cc_num                 object
 3   merchant               object
 4   category               object
 5   amt                    float64
 6   first                  object
 7   last                   object
 8   gender                 object
 9   street                 object
 10  city                   object
 11  state                  object
 12  zip                    object
 13  lat                    float64
 14  long                   float64
 15  city_pop               int64
 16  job                    object
 17  dob                    datetime64[ns]
 18  trans_num              object
 19  unix_time              int64
 20  merch_lat              float64
 21  merch_long             float64
 22  is_fraud               int64
dtypes: datetime64[ns](2), float64(5), int64(4), object(12)
memory usage: 325.1+ MB

**Summary:**

The data types of 4 columns has changed ("trans_date_trans_time" , "dob" , "cc_num" , "zip"). The others columns already had their suitable data types.